name: Generate file lists
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'generic'
      - 'workflow'
  pull_request:
  workflow_dispatch:

jobs:
  list-files:
    name: Generate source and destination file list
    runs-on: ubuntu-latest

    outputs:
      gcode-paths: ${{ steps.list-gcode-files.outputs.json }}

    steps:
      - name: Check out current branch
        uses: actions/checkout@v4
        with:
          path: current

      - name: Check out generator branch
        uses: actions/checkout@v4
        with:
          path: generator
          ref: generator

      - name: List Gcode Files using Tree
        id: list-gcode-files
        working-directory: current
        run: tree -P '*.g' -J --gitignore --noreport -fin . > gcode-files-raw.json

      - name: List Board Files using Tree
        id: list-board-files
        working-directory: current
        run: tree -P '*.txt' -J --gitignore --noreport -in ./boards > board-files-raw.json

      - name: Generate file and config JSON blobs
        uses: sergeysova/jq-action@v2
        id: reformat-tree-output
        with:
          cmd: |
            cd generator
            jq '[.[0] | recurse(.contents[]?) | select(.type == "file")] |
              map({ key: .name | sub("^\\."; ""), value: (.name | sub("^\\."; "") |
              sub("^/(system|(macros\/(movement|machine)))/"; "/sys/") |
              sub("^(?!/sys/)"; "/sys"))}) |
              from_entries' ../current/gcode-files-raw.json > gcode-files.json

            jq '[.[0] | recurse(.contents[]?) | select(.type == "file")] |
              map({ key: .name | sub("\\.txt$"; ""), value: .name }) |
              from_entries' ../current/board-files-raw.json > board-files.json

            jq '{
              downloadRoot: "https://raw.githubusercontent.com/${{ github.repository }}",
              downloadBranch: "${{ github.ref_name }}"
            }' -n > config.json

      - uses: EndBug/add-and-commit@v9
        with:
          add: gcode-files.json board-files.json config.json --force
          committer_name: GitHub Actions
          committer_email: actions@github.com
          message: "Update generator config and file lists"
          pull: --rebase --autostash
          cwd: "generator"