name: Update Config Generator site
on:
  push:
    tags-ignore:
      - '*'
    branches:
      - 'generator'
  workflow_dispatch:

jobs:
  upload-assets:
    name: Upload Github Pages artifact
    runs-on: ubuntu-latest
    steps:
      - name: Check out generator branch
        uses: actions/checkout@v4
    
      - name: Fix permissions
        run: |
          chmod -c -R +rX "." | while read line; do
            echo "::warning title=Invalid file permissions automatically fixed::$line"
          done

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: .

  deploy-pages:
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    runs-on: ubuntu-latest
    needs: upload-assets
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2